/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chrulri_droidtv_player_AVPlayer_OnUpdateListener */

#ifndef _Included_com_chrulri_droidtv_player_AVPlayer_OnUpdateListener
#define _Included_com_chrulri_droidtv_player_AVPlayer_OnUpdateListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
